Metadata:
  License: Apache-2.0
Description:
  'AWS CloudFormation template showing how to create an Amazon RDS Database Instance.**WARNING**
  This template creates an Amazon Relational Database Service database instance. You
  will be billed for the AWS resources used if you create a stack from this template.'
Parameters:
  DBName:
    Default: SalariumDatabase
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription:
      must begin with a letter and contain only alphanumeric
      characters.
  DBUser:
    NoEcho: 'true'
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription:
      must begin with a letter and contain only alphanumeric
      characters.
  DBPassword:
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
Resources:
  DB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref 'DBName'
      AllocatedStorage: '5'
      DBInstanceClass: db.t2.small
      Engine: MySQL
      EngineVersion: 5.6.40
      MasterUsername: !Ref 'DBUser'
      MasterUserPassword: !Ref 'DBPassword'
      DBParameterGroupName: !Ref 'RDSParamGroup'
  RDSParamGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Family: MySQL5.6
      Description: CloudFormation Database Parameter Group
      Parameters:
        autocommit: '1'
        general_log: '1'
        old_passwords: '0'
Outputs:
  JDBCConnectionString:
    Description: JDBC connection string for the database
    Value:
      !Join [
        '',
        [
          'jdbc:mysql://',
          !GetAtt [DB, Endpoint.Address],
          ':',
          !GetAtt [DB, Endpoint.Port],
          /,
          !Ref 'DBName',
        ],
      ]
